// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Food is the predicate function for food builders.
type Food func(*sql.Selector)

// Meal is the predicate function for meal builders.
type Meal func(*sql.Selector)

// Mealplan is the predicate function for mealplan builders.
type Mealplan func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
