// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/bluepsm/app/ent/food"
	"github.com/bluepsm/app/ent/meal"
	"github.com/bluepsm/app/ent/mealplan"
	"github.com/bluepsm/app/ent/predicate"
	"github.com/bluepsm/app/ent/user"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// MealplanUpdate is the builder for updating Mealplan entities.
type MealplanUpdate struct {
	config
	hooks      []Hook
	mutation   *MealplanMutation
	predicates []predicate.Mealplan
}

// Where adds a new predicate for the builder.
func (mu *MealplanUpdate) Where(ps ...predicate.Mealplan) *MealplanUpdate {
	mu.predicates = append(mu.predicates, ps...)
	return mu
}

// SetDate sets the date field.
func (mu *MealplanUpdate) SetDate(t time.Time) *MealplanUpdate {
	mu.mutation.SetDate(t)
	return mu
}

// SetOwnerID sets the owner edge to User by id.
func (mu *MealplanUpdate) SetOwnerID(id int) *MealplanUpdate {
	mu.mutation.SetOwnerID(id)
	return mu
}

// SetNillableOwnerID sets the owner edge to User by id if the given value is not nil.
func (mu *MealplanUpdate) SetNillableOwnerID(id *int) *MealplanUpdate {
	if id != nil {
		mu = mu.SetOwnerID(*id)
	}
	return mu
}

// SetOwner sets the owner edge to User.
func (mu *MealplanUpdate) SetOwner(u *User) *MealplanUpdate {
	return mu.SetOwnerID(u.ID)
}

// SetFoodsID sets the foods edge to Food by id.
func (mu *MealplanUpdate) SetFoodsID(id int) *MealplanUpdate {
	mu.mutation.SetFoodsID(id)
	return mu
}

// SetNillableFoodsID sets the foods edge to Food by id if the given value is not nil.
func (mu *MealplanUpdate) SetNillableFoodsID(id *int) *MealplanUpdate {
	if id != nil {
		mu = mu.SetFoodsID(*id)
	}
	return mu
}

// SetFoods sets the foods edge to Food.
func (mu *MealplanUpdate) SetFoods(f *Food) *MealplanUpdate {
	return mu.SetFoodsID(f.ID)
}

// SetMealsID sets the meals edge to Meal by id.
func (mu *MealplanUpdate) SetMealsID(id int) *MealplanUpdate {
	mu.mutation.SetMealsID(id)
	return mu
}

// SetNillableMealsID sets the meals edge to Meal by id if the given value is not nil.
func (mu *MealplanUpdate) SetNillableMealsID(id *int) *MealplanUpdate {
	if id != nil {
		mu = mu.SetMealsID(*id)
	}
	return mu
}

// SetMeals sets the meals edge to Meal.
func (mu *MealplanUpdate) SetMeals(m *Meal) *MealplanUpdate {
	return mu.SetMealsID(m.ID)
}

// Mutation returns the MealplanMutation object of the builder.
func (mu *MealplanUpdate) Mutation() *MealplanMutation {
	return mu.mutation
}

// ClearOwner clears the owner edge to User.
func (mu *MealplanUpdate) ClearOwner() *MealplanUpdate {
	mu.mutation.ClearOwner()
	return mu
}

// ClearFoods clears the foods edge to Food.
func (mu *MealplanUpdate) ClearFoods() *MealplanUpdate {
	mu.mutation.ClearFoods()
	return mu
}

// ClearMeals clears the meals edge to Meal.
func (mu *MealplanUpdate) ClearMeals() *MealplanUpdate {
	mu.mutation.ClearMeals()
	return mu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (mu *MealplanUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(mu.hooks) == 0 {
		affected, err = mu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MealplanMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mu.mutation = mutation
			affected, err = mu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mu.hooks) - 1; i >= 0; i-- {
			mut = mu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MealplanUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MealplanUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MealplanUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mu *MealplanUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   mealplan.Table,
			Columns: mealplan.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: mealplan.FieldID,
			},
		},
	}
	if ps := mu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.Date(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: mealplan.FieldDate,
		})
	}
	if mu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mealplan.OwnerTable,
			Columns: []string{mealplan.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mealplan.OwnerTable,
			Columns: []string{mealplan.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.FoodsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mealplan.FoodsTable,
			Columns: []string{mealplan.FoodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: food.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.FoodsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mealplan.FoodsTable,
			Columns: []string{mealplan.FoodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: food.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.MealsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mealplan.MealsTable,
			Columns: []string{mealplan.MealsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: meal.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.MealsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mealplan.MealsTable,
			Columns: []string{mealplan.MealsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: meal.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mealplan.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// MealplanUpdateOne is the builder for updating a single Mealplan entity.
type MealplanUpdateOne struct {
	config
	hooks    []Hook
	mutation *MealplanMutation
}

// SetDate sets the date field.
func (muo *MealplanUpdateOne) SetDate(t time.Time) *MealplanUpdateOne {
	muo.mutation.SetDate(t)
	return muo
}

// SetOwnerID sets the owner edge to User by id.
func (muo *MealplanUpdateOne) SetOwnerID(id int) *MealplanUpdateOne {
	muo.mutation.SetOwnerID(id)
	return muo
}

// SetNillableOwnerID sets the owner edge to User by id if the given value is not nil.
func (muo *MealplanUpdateOne) SetNillableOwnerID(id *int) *MealplanUpdateOne {
	if id != nil {
		muo = muo.SetOwnerID(*id)
	}
	return muo
}

// SetOwner sets the owner edge to User.
func (muo *MealplanUpdateOne) SetOwner(u *User) *MealplanUpdateOne {
	return muo.SetOwnerID(u.ID)
}

// SetFoodsID sets the foods edge to Food by id.
func (muo *MealplanUpdateOne) SetFoodsID(id int) *MealplanUpdateOne {
	muo.mutation.SetFoodsID(id)
	return muo
}

// SetNillableFoodsID sets the foods edge to Food by id if the given value is not nil.
func (muo *MealplanUpdateOne) SetNillableFoodsID(id *int) *MealplanUpdateOne {
	if id != nil {
		muo = muo.SetFoodsID(*id)
	}
	return muo
}

// SetFoods sets the foods edge to Food.
func (muo *MealplanUpdateOne) SetFoods(f *Food) *MealplanUpdateOne {
	return muo.SetFoodsID(f.ID)
}

// SetMealsID sets the meals edge to Meal by id.
func (muo *MealplanUpdateOne) SetMealsID(id int) *MealplanUpdateOne {
	muo.mutation.SetMealsID(id)
	return muo
}

// SetNillableMealsID sets the meals edge to Meal by id if the given value is not nil.
func (muo *MealplanUpdateOne) SetNillableMealsID(id *int) *MealplanUpdateOne {
	if id != nil {
		muo = muo.SetMealsID(*id)
	}
	return muo
}

// SetMeals sets the meals edge to Meal.
func (muo *MealplanUpdateOne) SetMeals(m *Meal) *MealplanUpdateOne {
	return muo.SetMealsID(m.ID)
}

// Mutation returns the MealplanMutation object of the builder.
func (muo *MealplanUpdateOne) Mutation() *MealplanMutation {
	return muo.mutation
}

// ClearOwner clears the owner edge to User.
func (muo *MealplanUpdateOne) ClearOwner() *MealplanUpdateOne {
	muo.mutation.ClearOwner()
	return muo
}

// ClearFoods clears the foods edge to Food.
func (muo *MealplanUpdateOne) ClearFoods() *MealplanUpdateOne {
	muo.mutation.ClearFoods()
	return muo
}

// ClearMeals clears the meals edge to Meal.
func (muo *MealplanUpdateOne) ClearMeals() *MealplanUpdateOne {
	muo.mutation.ClearMeals()
	return muo
}

// Save executes the query and returns the updated entity.
func (muo *MealplanUpdateOne) Save(ctx context.Context) (*Mealplan, error) {

	var (
		err  error
		node *Mealplan
	)
	if len(muo.hooks) == 0 {
		node, err = muo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MealplanMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			muo.mutation = mutation
			node, err = muo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(muo.hooks) - 1; i >= 0; i-- {
			mut = muo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, muo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MealplanUpdateOne) SaveX(ctx context.Context) *Mealplan {
	m, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return m
}

// Exec executes the query on the entity.
func (muo *MealplanUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MealplanUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (muo *MealplanUpdateOne) sqlSave(ctx context.Context) (m *Mealplan, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   mealplan.Table,
			Columns: mealplan.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: mealplan.FieldID,
			},
		},
	}
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Mealplan.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := muo.mutation.Date(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: mealplan.FieldDate,
		})
	}
	if muo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mealplan.OwnerTable,
			Columns: []string{mealplan.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mealplan.OwnerTable,
			Columns: []string{mealplan.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.FoodsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mealplan.FoodsTable,
			Columns: []string{mealplan.FoodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: food.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.FoodsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mealplan.FoodsTable,
			Columns: []string{mealplan.FoodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: food.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.MealsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mealplan.MealsTable,
			Columns: []string{mealplan.MealsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: meal.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.MealsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mealplan.MealsTable,
			Columns: []string{mealplan.MealsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: meal.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	m = &Mealplan{config: muo.config}
	_spec.Assign = m.assignValues
	_spec.ScanValues = m.scanValues()
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mealplan.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return m, nil
}
