// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// FoodsColumns holds the columns for the "foods" table.
	FoodsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "ing", Type: field.TypeString},
		{Name: "calories", Type: field.TypeInt},
		{Name: "added", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeInt, Nullable: true},
	}
	// FoodsTable holds the schema information for the "foods" table.
	FoodsTable = &schema.Table{
		Name:       "foods",
		Columns:    FoodsColumns,
		PrimaryKey: []*schema.Column{FoodsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "foods_users_foods",
				Columns: []*schema.Column{FoodsColumns[5]},

				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// MealsColumns holds the columns for the "meals" table.
	MealsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// MealsTable holds the schema information for the "meals" table.
	MealsTable = &schema.Table{
		Name:        "meals",
		Columns:     MealsColumns,
		PrimaryKey:  []*schema.Column{MealsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// MealplansColumns holds the columns for the "mealplans" table.
	MealplansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "date", Type: field.TypeTime},
		{Name: "menu_id", Type: field.TypeInt, Nullable: true},
		{Name: "meal_id", Type: field.TypeInt, Nullable: true},
		{Name: "user_id", Type: field.TypeInt, Nullable: true},
	}
	// MealplansTable holds the schema information for the "mealplans" table.
	MealplansTable = &schema.Table{
		Name:       "mealplans",
		Columns:    MealplansColumns,
		PrimaryKey: []*schema.Column{MealplansColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "mealplans_foods_mealplans",
				Columns: []*schema.Column{MealplansColumns[2]},

				RefColumns: []*schema.Column{FoodsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "mealplans_meals_mealplans",
				Columns: []*schema.Column{MealplansColumns[3]},

				RefColumns: []*schema.Column{MealsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "mealplans_users_mealplans",
				Columns: []*schema.Column{MealplansColumns[4]},

				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:        "users",
		Columns:     UsersColumns,
		PrimaryKey:  []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FoodsTable,
		MealsTable,
		MealplansTable,
		UsersTable,
	}
)

func init() {
	FoodsTable.ForeignKeys[0].RefTable = UsersTable
	MealplansTable.ForeignKeys[0].RefTable = FoodsTable
	MealplansTable.ForeignKeys[1].RefTable = MealsTable
	MealplansTable.ForeignKeys[2].RefTable = UsersTable
}
