// Code generated by entc, DO NOT EDIT.

package meal

const (
	// Label holds the string label denoting the meal type in the database.
	Label = "meal"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgeMealplans holds the string denoting the mealplans edge name in mutations.
	EdgeMealplans = "mealplans"

	// Table holds the table name of the meal in the database.
	Table = "meals"
	// MealplansTable is the table the holds the mealplans relation/edge.
	MealplansTable = "mealplans"
	// MealplansInverseTable is the table name for the Mealplan entity.
	// It exists in this package in order to avoid circular dependency with the "mealplan" package.
	MealplansInverseTable = "mealplans"
	// MealplansColumn is the table column denoting the mealplans relation/edge.
	MealplansColumn = "meal_id"
)

// Columns holds all SQL columns for meal fields.
var Columns = []string{
	FieldID,
	FieldName,
}
