/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersMealplan
 */
export interface ControllersMealplan {
    /**
     * 
     * @type {string}
     * @memberof ControllersMealplan
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersMealplan
     */
    food?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersMealplan
     */
    meal?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersMealplan
     */
    owner?: number;
}

export function ControllersMealplanFromJSON(json: any): ControllersMealplan {
    return ControllersMealplanFromJSONTyped(json, false);
}

export function ControllersMealplanFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersMealplan {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': !exists(json, 'date') ? undefined : json['date'],
        'food': !exists(json, 'food') ? undefined : json['food'],
        'meal': !exists(json, 'meal') ? undefined : json['meal'],
        'owner': !exists(json, 'owner') ? undefined : json['owner'],
    };
}

export function ControllersMealplanToJSON(value?: ControllersMealplan | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date,
        'food': value.food,
        'meal': value.meal,
        'owner': value.owner,
    };
}


