/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntMealplan,
    EntMealplanFromJSON,
    EntMealplanFromJSONTyped,
    EntMealplanToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntFoodEdges
 */
export interface EntFoodEdges {
    /**
     * Mealplans holds the value of the mealplans edge.
     * @type {Array<EntMealplan>}
     * @memberof EntFoodEdges
     */
    mealplans?: Array<EntMealplan>;
    /**
     * 
     * @type {EntUser}
     * @memberof EntFoodEdges
     */
    owner?: EntUser;
}

export function EntFoodEdgesFromJSON(json: any): EntFoodEdges {
    return EntFoodEdgesFromJSONTyped(json, false);
}

export function EntFoodEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntFoodEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mealplans': !exists(json, 'mealplans') ? undefined : ((json['mealplans'] as Array<any>).map(EntMealplanFromJSON)),
        'owner': !exists(json, 'owner') ? undefined : EntUserFromJSON(json['owner']),
    };
}

export function EntFoodEdgesToJSON(value?: EntFoodEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mealplans': value.mealplans === undefined ? undefined : ((value.mealplans as Array<any>).map(EntMealplanToJSON)),
        'owner': EntUserToJSON(value.owner),
    };
}


