/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntFoodEdges,
    EntFoodEdgesFromJSON,
    EntFoodEdgesFromJSONTyped,
    EntFoodEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntFood
 */
export interface EntFood {
    /**
     * Added holds the value of the "added" field.
     * @type {string}
     * @memberof EntFood
     */
    added?: string;
    /**
     * Calories holds the value of the "calories" field.
     * @type {number}
     * @memberof EntFood
     */
    calories?: number;
    /**
     * 
     * @type {EntFoodEdges}
     * @memberof EntFood
     */
    edges?: EntFoodEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntFood
     */
    id?: number;
    /**
     * Ing holds the value of the "ing" field.
     * @type {string}
     * @memberof EntFood
     */
    ing?: string;
    /**
     * Name holds the value of the "name" field.
     * @type {string}
     * @memberof EntFood
     */
    name?: string;
}

export function EntFoodFromJSON(json: any): EntFood {
    return EntFoodFromJSONTyped(json, false);
}

export function EntFoodFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntFood {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'added': !exists(json, 'added') ? undefined : json['added'],
        'calories': !exists(json, 'calories') ? undefined : json['calories'],
        'edges': !exists(json, 'edges') ? undefined : EntFoodEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ing': !exists(json, 'ing') ? undefined : json['ing'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function EntFoodToJSON(value?: EntFood | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'added': value.added,
        'calories': value.calories,
        'edges': EntFoodEdgesToJSON(value.edges),
        'id': value.id,
        'ing': value.ing,
        'name': value.name,
    };
}


