/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntMealplan,
    EntMealplanFromJSON,
    EntMealplanFromJSONTyped,
    EntMealplanToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntMealEdges
 */
export interface EntMealEdges {
    /**
     * Mealplans holds the value of the mealplans edge.
     * @type {Array<EntMealplan>}
     * @memberof EntMealEdges
     */
    mealplans?: Array<EntMealplan>;
}

export function EntMealEdgesFromJSON(json: any): EntMealEdges {
    return EntMealEdgesFromJSONTyped(json, false);
}

export function EntMealEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntMealEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mealplans': !exists(json, 'mealplans') ? undefined : ((json['mealplans'] as Array<any>).map(EntMealplanFromJSON)),
    };
}

export function EntMealEdgesToJSON(value?: EntMealEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mealplans': value.mealplans === undefined ? undefined : ((value.mealplans as Array<any>).map(EntMealplanToJSON)),
    };
}


