/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntFood,
    EntFoodFromJSON,
    EntFoodFromJSONTyped,
    EntFoodToJSON,
    EntMeal,
    EntMealFromJSON,
    EntMealFromJSONTyped,
    EntMealToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntMealplanEdges
 */
export interface EntMealplanEdges {
    /**
     * 
     * @type {EntFood}
     * @memberof EntMealplanEdges
     */
    foods?: EntFood;
    /**
     * 
     * @type {EntMeal}
     * @memberof EntMealplanEdges
     */
    meals?: EntMeal;
    /**
     * 
     * @type {EntUser}
     * @memberof EntMealplanEdges
     */
    owner?: EntUser;
}

export function EntMealplanEdgesFromJSON(json: any): EntMealplanEdges {
    return EntMealplanEdgesFromJSONTyped(json, false);
}

export function EntMealplanEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntMealplanEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'foods': !exists(json, 'Foods') ? undefined : EntFoodFromJSON(json['Foods']),
        'meals': !exists(json, 'Meals') ? undefined : EntMealFromJSON(json['Meals']),
        'owner': !exists(json, 'Owner') ? undefined : EntUserFromJSON(json['Owner']),
    };
}

export function EntMealplanEdgesToJSON(value?: EntMealplanEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'foods': EntFoodToJSON(value.foods),
        'meals': EntMealToJSON(value.meals),
        'owner': EntUserToJSON(value.owner),
    };
}


