/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntFood,
    EntFoodFromJSON,
    EntFoodFromJSONTyped,
    EntFoodToJSON,
    EntMealplan,
    EntMealplanFromJSON,
    EntMealplanFromJSONTyped,
    EntMealplanToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntUserEdges
 */
export interface EntUserEdges {
    /**
     * Foods holds the value of the foods edge.
     * @type {Array<EntFood>}
     * @memberof EntUserEdges
     */
    foods?: Array<EntFood>;
    /**
     * Mealplans holds the value of the mealplans edge.
     * @type {Array<EntMealplan>}
     * @memberof EntUserEdges
     */
    mealplans?: Array<EntMealplan>;
}

export function EntUserEdgesFromJSON(json: any): EntUserEdges {
    return EntUserEdgesFromJSONTyped(json, false);
}

export function EntUserEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntUserEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'foods': !exists(json, 'foods') ? undefined : ((json['foods'] as Array<any>).map(EntFoodFromJSON)),
        'mealplans': !exists(json, 'mealplans') ? undefined : ((json['mealplans'] as Array<any>).map(EntMealplanFromJSON)),
    };
}

export function EntUserEdgesToJSON(value?: EntUserEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'foods': value.foods === undefined ? undefined : ((value.foods as Array<any>).map(EntFoodToJSON)),
        'mealplans': value.mealplans === undefined ? undefined : ((value.mealplans as Array<any>).map(EntMealplanToJSON)),
    };
}


